apiVersion: v1 
kind: Pod 
metadata:
  name: nginx-dev-pod
  labels:
    app: nginx-dev 
spec:
  containers:
    - name: nhinx-dev
      image: nginx:latest
      resources:
        requests:
          memory: 64Mi
          cpu: 100m
        limits:
          memory: 128Mi
          cpu: 500m
        